AWSTemplateFormatVersion: 2010-09-09

Resources:
  RanaPortfolioBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: rana.lol
      PublicAccessBlockConfiguration:
          BlockPublicAcls: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  RanaPortfolioBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref RanaPortfolioBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action:
              - s3:GetObject
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref RanaPortfolioBucket
                - '/*'

Outputs:
  RanaPortfolioBucketURL:
    Description: URL of the deployed React app in S3 bucket
    Value: !GetAtt RanaPortfolioBucket.WebsiteURL
