AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  PortfolioDomainName:
    Description: Website Domain Name
    Type: String
    Default: rana.lol

Resources:
  # Creating resources for my personal website
  PortfolioWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref PortfolioDomainName
      BucketEncryption:
        ServerSideEncryptionConfiguration: 
          -
            ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      # PublicAccessBlockConfiguration:
      #     BlockPublicAcls: false
      # OwnershipControls:
      #   Rules:
      #     - ObjectOwnership: ObjectWriter
      # WebsiteConfiguration:
        # IndexDocument: index.html
        # ErrorDocument: index.html

  PortfolioHostedZone:
    Type: 'AWS::Route53::HostedZone'
    Properties:
      Name: !Ref PortfolioDomainName 

  PortfolioCertificate:
    Type: 'AWS::CertificateManager::Certificate'
    Properties:
      DomainName: !Ref PortfolioDomainName
      DomainValidationOptions:
        - DomainName: !Ref PortfolioDomainName
          HostedZoneId: !Ref PortfolioHostedZone
      SubjectAlternativeNames: 
        - "*.rana.lol"
      ValidationMethod: DNS

  PortfolioWebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn: PortfolioCloudFrontDistribution
    Properties:
      Bucket: !Ref PortfolioWebsiteBucket
      PolicyDocument:
        Statement:
          - Sid: CloudFrontDistributionAccess
            Effect: Allow
            Principal:
              CanonicalUser: !GetAtt PortfolioCloudFrontOriginAccessIdentity.S3CanonicalUserId
            Action:
              s3:GetObject
            Resource: !Join [ "", [ "arn:aws:s3:::", !Ref PortfolioWebsiteBucket, "/*" ]]
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::248073758255:distribution/${PortfolioCloudFrontDistribution}"
          # - Sid: PublicReadGetObject
          #   Effect: Allow
          #   Principal: '*'
          #   Action:
          #     - s3:GetObject
          #   Resource: !Join
          #     - ''
          #     - - 'arn:aws:s3:::'
          #       - !Ref PortfolioWebsiteBucket
          #       - '/*'

  # # Creating certificate in certificate manager    
  # CloudFrontOriginAccessControl:
  #   Type: AWS::CloudFront::OriginAccessControl
  #   Properties:
  #     OriginAccessControlConfig:
  #       Description: "Origin Access Control (OAC)"
  #       Name: portfolio-website-oac
  #       OriginAccessControlOriginType: s3
  #       SigningBehaviour: always
  #       SigningProtocol: sigv4

  PortfolioCloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub 'CloudFront OAI for ${PortfolioDomainName}'

  PortfolioCloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution" 
    DependsOn: 
      - PortfolioWebsiteBucket
      - PortfolioCloudFrontOriginAccessIdentity
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref PortfolioDomainName
        ViewerCertificate:
          AcmCertificateArn: !Ref PortfolioCertificate
          SslSupportMethod: sni-only
        CustomErrorResponses:
          - ErrorCachingMinTTL: 300
            ErrorCode: 403
            ResponseCode: 404
            ResponsePagePath: /index.html
        DefaultCacheBehavior:
          ViewerProtocolPolicy: https-only
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          DefaultTTL: 3600
          ForwardedValues:
            Cookies:
                Forward: none
            QueryString: false
          MaxTTL: 86400
          MinTTL: 60
          TargetOriginId: personal-website-host-origin
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: "index.html"
        Enabled: true
        HttpVersion: http2
        Origins:
          - DomainName: 
              !Join [ "", [ !Ref PortfolioWebsiteBucket, ".s3.amazonaws.com" ] ]
            Id: personal-website-host-origin
            S3OriginConfig:
              OriginAccessIdentity:
                !Join [ "", [ "origin-access-identity/cloudfront/", !Ref PortfolioCloudFrontOriginAccessIdentity ] ]
            #   OriginAccessIdentity: ""
            # OriginAccessControlId: !GetAtt CloudFrontOriginAccessControl.Id
        PriceClass: PriceClass_All

  DNSRecord:
    Type: AWS::Route53::RecordSet
    DependsOn: PortfolioCloudFrontDistribution
    Properties:
      HostedZoneId: !Ref PortfolioHostedZone
      Name: !Ref PortfolioDomainName
      Type: A
      AliasTarget: 
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt PortfolioCloudFrontDistribution.DomainName
      # Comment: DNS name for cloud front
      # Name: !Ref PortfolioDomainName
      # Type: A
      # ResourceRecords:
      #   - !GetAtt CloudFrontDistribution.DomainName
 

Outputs:
  PortfolioWebsiteBucket:
    Description: Bucket name of the portfolio website
    Value: !Ref PortfolioWebsiteBucket
  PortfolioWebsiteBucketURL:
    Description: URL of the deployed React app in S3 bucket
    Value: !GetAtt PortfolioWebsiteBucket.WebsiteURL
  PortfolioHostedZone:
    Description: Name of Hosted Zone for the portfolio website
    Value: !Ref PortfolioHostedZone
  PortfolioCertificate:
    Description: Certificate of the portfolio website
    Value: !Ref PortfolioCertificate

